@startuml

ditaa
 +----+                +-------------+                +----+
 | F3 |<---------------| 0.Aristotle |--------------->| F0 |
 +----+         Right  +-------------+  Left          +----+
    ^                                                   ^
    |                                                   |
    | Left                                              | Right
    |                                                   |
+----------+                                        +---------+
| 3.Diogen |                                        | 1.Plato |
+----------+                                        +---------+
    |                                                   |
    | Right                                             | Left
    |                                                   |
    v                                                   v
 +----+                +------------+                 +----+
 | F2 |<---------------| 2.Socrates |---------------->| F1 |
 +----+          Left  +------------+  Right          +----+

@enduml
